# gz topic published by Sensors plugin
- ros_topic_name: "camera_head/depth/camera_info"
  gz_topic_name: "camera_head/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
  lazy: true

# gz topic published by Sensors plugin
- ros_topic_name: "camera_head/depth/color/points"
  gz_topic_name: "camera_head/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
  lazy: true

# # âœ… Correct clock bridging
- topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
